[project]
site_name = "Xiyao Zhuang"
site_url = "https://xiyaozhuang.github.io/"
site_author = "Xiyao Zhuang"

copyright = "Copyright &copy; 2026 Xiyao Zhuang"

repo_name = "xiyaozhuang.github.io"
repo_url = "https://github.com/xiyaozhuang/xiyaozhuang.github.io"

[project.theme]
language = "en"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.theme.icon]
logo = "lucide/terminal"
repo = "fontawesome/brands/github"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/xiyaozhuang"
